version: "3.7"

services:

  rabbitmq:
    image: rabbitmq:management
    volumes:
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - trabajo-titulo

networks:
  trabajo-titulo:
    external: true

volumes:
  config: